#!/bin/bash
filename="/Users/$USER/Library/Application Support/Übersicht/widgets/pretty-weather.widget/index.coffee";
out=$(whereami | awk 'FNR == 1 {print $2};  FNR == 2 {print $2}' | sed "N;s/\n/,/")  
out=$(echo "location = '"$out"' # Updated!");
in=$(sed -n '2p' "$filename");

sed -i -e "s/${in}/${out}/g" "$filename"
